---
###############################################################
#                Authelia minimal configuration               #
###############################################################

jwt_secret: unsecure_secret

server:
  address: 'tcp://:9091'
  asset_path: '/config/assets/'
  tls:
    certificate: /pki/public.backend.crt
    key: /pki/private.backend.pem
  endpoints:
    authz:
      caddy:
        implementation: ForwardAuth
        authn_strategies: []

log:
  level: debug

authentication_backend:
  file:
    path: /config/users.yml

session:
  secret: unsecure_session_secret
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  remember_me: 1y
  cookies:
    - domain: 'example.com'
      authelia_url: 'https://login.example.com:8080'

storage:
  encryption_key: a_not_so_secure_encryption_key
  local:
    path: /config/db.sqlite

access_control:
  default_policy: bypass
  rules:
    - domain: "public.example.com"
      policy: bypass
    - domain: "admin.example.com"
      policy: two_factor
    - domain: "secure.example.com"
      policy: two_factor
    - domain: "singlefactor.example.com"
      policy: one_factor

notifier:
  smtp:
    address: 'smtp://smtp:1025'
    sender: admin@example.com
    disable_require_tls: true
...
