---
version: '3'
services:
  authelia-backend:
    volumes:
      - './DuoPush/configuration.yml:/config/configuration.yml:ro'
      - './DuoPush/users.yml:/config/users.yml'
      - './common/pki:/pki:ro'
      - '/tmp:/tmp'
    user: ${USER_ID}:${GROUP_ID}
...
